'''
Constants for support apis
'''
SWITCHLIST = 'switchlist'
SWITCHDESC = 'switchdesc'
SWITCHFLOW = 'switchflow'
SWITCHPORTS = 'switchports'
SWITCHPORTSDESC = 'switchportsdesc'
SWITCHGROUP = 'switchgroup'
SWITCHGROUPDESC = 'switchgroupdesc'
SWITCHGROUPFEATURES = 'switchgroupfeatures'
SWITCHMETER = 'switchmeter'
SWITCHMETERCONFIG = 'switchmeterconfig'
SWITCHMETERFEATURES = 'switchmeterfeatures'
ADDFLOWENTRY = 'addflowentry'
MODIFYFLOWENTRY = 'modifyflowentry'
DELETEFLOWENTRY = 'deleteflowentry'
CLEARFLOWENTRY = 'clearflowentry'
